### ISSUE TITLE
Does not seem to work ...

### ISSUE THREAD

**Issue by ChrisGitIt** [workeffortwaste/core-serp-vitals#2]
Hi and thanks for your extension!

Somehow it does not seem to work. I got a Chrome UX Report API key, installed the extension and added the key. Then nothing happens on my SERP.

I have checked the key and GCP says its fine and active. I checked the options of your extension and out of the box, there is seems nothing that I would need to "active" somehow.

Finally I restarted Chrome and checked again. Nothing is happening.

Is it mandatory to be logged into my G-Account on Chrome? That's the only thing I haven't checked because I don't trust Chrome with any kind of my surf data.

Greetings,

Chris

**Comment by workeffortwaste** [comment]
Have you tried searching for a generic term like 'test'? It could be that for your search queries there are no results available in the CrUX report.
