### ISSUE TITLE
Bad selector

### ISSUE THREAD

**Issue by niutech** [workeffortwaste/core-serp-vitals#5]
The selector `#search .g div > a[ping][data-ved]` does not found any links. Please remove `[ping]` from it.

**Comment by workeffortwaste** [comment]
It's still working for me.
![image](https://user-images.githubusercontent.com/49479599/137274606-b0c9d8a4-cf62-4432-b859-e170184378f0.png)

Can you show me a screenshot and the HTML of a SERP where it doesn't work please?

**Comment by niutech** [comment]
Sure, it doesn't work on any SERP in www.google.com in Opera, see screenshot:

![obraz](https://user-images.githubusercontent.com/384997/137287772-e89c458b-bb79-49c0-9d06-862074475d68.png)

Maybe my adblocker removes `ping` attributes?

**Comment by workeffortwaste** [comment]
Thanks for that, it looks like Google serves HTML without the `ping` attribute to the Opera browser. I'll get the plugin updated in a minute.

**Comment by workeffortwaste** [comment]
An updated version is now published on the store, can you check it works as expected for you so I can close the issue.

**Comment by niutech** [comment]
There is still an issue with the selector  `#search .g div > a[data-ved]` - it finds also the dropdown menu link:

![obraz](https://user-images.githubusercontent.com/384997/137320502-c7d04e21-c226-479c-b848-8fa3f8e8872a.png)

Because of that I get the error 400 INVALID_ARGUMENT from https://chromeuxreport.googleapis.com/batch/: `invalid url: "#"`.

So please modify the selector to `#search .g > div > div > div > a[data-ved][href^="http"]`.

**Comment by workeffortwaste** [comment]
Thanks, I'm just waiting for an updated version to get accepted onto the store.

**Comment by workeffortwaste** [comment]
Can you check it now please.

**Comment by niutech** [comment]
Now it works, thanks a lot!

![obraz](https://user-images.githubusercontent.com/384997/137457633-9d69ee37-6072-4182-8d84-7f4f4c84d1d6.png)
