### ISSUE TITLE
Minor stylistic issue on dark mode

### ISSUE THREAD

**Issue by Cherry** [workeffortwaste/core-serp-vitals#9]
![Core SERP vitals Chrome Extension - showing minor style issue with border color in dark mode](https://user-images.githubusercontent.com/856748/169382837-cad8a7ea-d43b-4280-b87a-a4109cc9bfb5.png)

This is using the native dark mode in Google Search. The border color could likely do with being toned down a little when in dark mode.

**Comment by workeffortwaste** [comment]
I'd completely forgotten about dark mode. 🙈

I'll get that sorted tomorrow.

**Comment by workeffortwaste** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/49479599/169485169-b988351c-61fa-4f49-a884-6b456c8bf60a.png">

This is now fixed, it'll take a little while for the update to make its way through the approval process on the store.

**Comment by Cherry** [comment]
Looks great, thank you so much for the quick turnaround!
